INSERT INTO public.projects (
        id,
        title,
        slug,
        description,
        long_description,
        category,
        image_url,
        technologies,
        github_url,
        demo_url,
        status,
        featured,
        metrics,
        sort_order,
        published,
        created_at,
        updated_at,
        excerpt,
        start_date,
        end_date,
        seo_title,
        seo_description
    )
VALUES (
        gen_random_uuid(),
        'Neural Analytics Dashboard',
        'neural-analytics-dashboard',
        'Real-time machine learning insights platform processing 10TB+ daily data with advanced neural network visualization and predictive analytics.',
        'Built a comprehensive analytics platform that transforms complex ML model outputs into intuitive visualizations. Features real-time data processing with Apache Spark, custom neural network architectures for anomaly detection, and interactive dashboards built with React and D3.js. Achieved 40% improvement in decision-making speed for data science teams.',
        'AI/ML',
        '/src/assets/project-neural-dashboard.jpg',
        ARRAY ['Python', 'TensorFlow', 'React', 'Apache Spark', 'PostgreSQL', 'Docker'],
        'https://github.com/alexneural/neural-dashboard',
        'https://neural-dashboard.alexneural.dev',
        'Production',
        true,
        '[{"label": "Data Processed", "value": "10TB/day"}, {"label": "Model Accuracy", "value": "94.2%"}, {"label": "Response Time", "value": "<200ms"}, {"label": "Users", "value": "1000+"}]'::jsonb,
        0,
        true,
        now(),
        now(),
        'Real-time machine learning insights platform',
        '2023-01-15',
        '2023-06-30',
        'Neural Analytics Dashboard - AI/ML Insights',
        'Real-time machine learning insights platform with advanced neural network visualization and predictive analytics.'
    ),
    (
        gen_random_uuid(),
        'AI-Powered Personal Assistant',
        'ai-powered-personal-assistant',
        'Cross-platform mobile application with advanced NLP capabilities, voice recognition, and smart home integration using Flutter and custom ML models.',
        'Developed an intelligent mobile assistant that understands natural language commands and integrates with IoT devices. Implemented custom transformer models for intent recognition, real-time speech processing, and context-aware responses. The app features offline capabilities and privacy-first design with on-device ML processing.',
        'Mobile/AI',
        '/src/assets/project-ai-assistant.jpg',
        ARRAY ['Flutter', 'PyTorch', 'Node.js', 'TensorFlow Lite', 'Firebase', 'WebRTC'],
        'https://github.com/alexneural/ai-assistant',
        'https://apps.apple.com/ai-assistant',
        'Production',
        true,
        '[{"label": "Recognition Accuracy", "value": "97.5%"}, {"label": "Response Time", "value": "1.2s"}, {"label": "Downloads", "value": "50K+"}, {"label": "Rating", "value": "4.8/5"}]'::jsonb,
        0,
        true,
        now(),
        now(),
        'Cross-platform mobile application with advanced NLP capabilities',
        '2022-09-01',
        '2023-03-15',
        'AI-Powered Personal Assistant - Mobile NLP',
        'Cross-platform mobile application with advanced NLP capabilities, voice recognition, and smart home integration.'
    ),
    (
        gen_random_uuid(),
        'Distributed Data Pipeline',
        'distributed-data-pipeline',
        'Scalable real-time data processing system using Apache Kafka, handling millions of events per second with fault tolerance and monitoring.',
        'Architected and implemented a robust data pipeline capable of processing streaming data from multiple sources. Built with microservices architecture, featuring automated scaling, dead letter queues, and comprehensive monitoring. Reduced data processing latency by 75% and improved system reliability to 99.95% uptime.',
        'Data Engineering',
        '/src/assets/project-data-pipeline.jpg',
        ARRAY ['Apache Kafka', 'Python', 'Kubernetes', 'Elasticsearch', 'Redis', 'Grafana'],
        'https://github.com/alexneural/data-pipeline',
        'https://pipeline-demo.alexneural.dev',
        'Production',
        false,
        '[{"label": "Events/Second", "value": "2M+"}, {"label": "Latency Reduction", "value": "75%"}, {"label": "Uptime", "value": "99.95%"}, {"label": "Cost Savings", "value": "$100K/yr"}]'::jsonb,
        0,
        true,
        now(),
        now(),
        'Scalable real-time data processing system using Apache Kafka',
        '2023-04-01',
        '2023-10-01',
        'Distributed Data Pipeline - Real-time Processing',
        'Scalable real-time data processing system using Apache Kafka, handling millions of events per second.'
    ) ON CONFLICT (slug) DO NOTHING;