// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://kmsalrouzjnwejevtmdf.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imttc2Fscm91empud2VqZXZ0bWRmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTkwOTYyNzUsImV4cCI6MjA3NDY3MjI3NX0.dr5gvINP3j5jBCYYqRd_Smyllv81uequCYvvREVxhlg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});